// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CameronHonis/chess-arbitrator/app (interfaces: AppServiceI)
//
// Generated by this command:
//
//	mockgen -destination mock/app_service_mock.go . AppServiceI
//

// Package mock_app is a generated GoMock package.
package mock_app

import (
	reflect "reflect"

	service "github.com/CameronHonis/service"
	gomock "go.uber.org/mock/gomock"
)

// MockAppServiceI is a mock of AppServiceI interface.
type MockAppServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockAppServiceIMockRecorder
}

// MockAppServiceIMockRecorder is the mock recorder for MockAppServiceI.
type MockAppServiceIMockRecorder struct {
	mock *MockAppServiceI
}

// NewMockAppServiceI creates a new mock instance.
func NewMockAppServiceI(ctrl *gomock.Controller) *MockAppServiceI {
	mock := &MockAppServiceI{ctrl: ctrl}
	mock.recorder = &MockAppServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppServiceI) EXPECT() *MockAppServiceIMockRecorder {
	return m.recorder
}

// AddDependency mocks base method.
func (m *MockAppServiceI) AddDependency(arg0 service.ServiceI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDependency", arg0)
}

// AddDependency indicates an expected call of AddDependency.
func (mr *MockAppServiceIMockRecorder) AddDependency(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDependency", reflect.TypeOf((*MockAppServiceI)(nil).AddDependency), arg0)
}

// AddEventListener mocks base method.
func (m *MockAppServiceI) AddEventListener(arg0 service.EventVariant, arg1 service.EventHandler) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventListener", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// AddEventListener indicates an expected call of AddEventListener.
func (mr *MockAppServiceIMockRecorder) AddEventListener(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventListener", reflect.TypeOf((*MockAppServiceI)(nil).AddEventListener), arg0, arg1)
}

// Config mocks base method.
func (m *MockAppServiceI) Config() service.ConfigI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(service.ConfigI)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockAppServiceIMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockAppServiceI)(nil).Config))
}

// Dependencies mocks base method.
func (m *MockAppServiceI) Dependencies() []service.ServiceI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dependencies")
	ret0, _ := ret[0].([]service.ServiceI)
	return ret0
}

// Dependencies indicates an expected call of Dependencies.
func (mr *MockAppServiceIMockRecorder) Dependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dependencies", reflect.TypeOf((*MockAppServiceI)(nil).Dependencies))
}

// Dispatch mocks base method.
func (m *MockAppServiceI) Dispatch(arg0 service.EventI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Dispatch", arg0)
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockAppServiceIMockRecorder) Dispatch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockAppServiceI)(nil).Dispatch), arg0)
}

// OnStart mocks base method.
func (m *MockAppServiceI) OnStart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStart")
}

// OnStart indicates an expected call of OnStart.
func (mr *MockAppServiceIMockRecorder) OnStart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStart", reflect.TypeOf((*MockAppServiceI)(nil).OnStart))
}

// RemoveEventListener mocks base method.
func (m *MockAppServiceI) RemoveEventListener(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveEventListener", arg0)
}

// RemoveEventListener indicates an expected call of RemoveEventListener.
func (mr *MockAppServiceIMockRecorder) RemoveEventListener(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEventListener", reflect.TypeOf((*MockAppServiceI)(nil).RemoveEventListener), arg0)
}

// SetParent mocks base method.
func (m *MockAppServiceI) SetParent(arg0 service.ServiceI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetParent", arg0)
}

// SetParent indicates an expected call of SetParent.
func (mr *MockAppServiceIMockRecorder) SetParent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParent", reflect.TypeOf((*MockAppServiceI)(nil).SetParent), arg0)
}

// Start mocks base method.
func (m *MockAppServiceI) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockAppServiceIMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAppServiceI)(nil).Start))
}
