// Code generated by MockGen. DO NOT EDIT.
// Source: ../matcher/matcher_service.go
//
// Generated by this command:
//
//	mockgen -source=../matcher/matcher_service.go -destination mocks/matcher_service_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	chess "github.com/CameronHonis/chess"
	models "github.com/CameronHonis/chess-arbitrator/models"
	service "github.com/CameronHonis/service"
	set "github.com/CameronHonis/set"
	gomock "go.uber.org/mock/gomock"
)

// MockMatcherServiceI is a mock of MatcherServiceI interface.
type MockMatcherServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockMatcherServiceIMockRecorder
}

// MockMatcherServiceIMockRecorder is the mock recorder for MockMatcherServiceI.
type MockMatcherServiceIMockRecorder struct {
	mock *MockMatcherServiceI
}

// NewMockMatcherServiceI creates a new mock instance.
func NewMockMatcherServiceI(ctrl *gomock.Controller) *MockMatcherServiceI {
	mock := &MockMatcherServiceI{ctrl: ctrl}
	mock.recorder = &MockMatcherServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatcherServiceI) EXPECT() *MockMatcherServiceIMockRecorder {
	return m.recorder
}

// AcceptChallenge mocks base method.
func (m *MockMatcherServiceI) AcceptChallenge(challengedKey, challengerKey models.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptChallenge", challengedKey, challengerKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptChallenge indicates an expected call of AcceptChallenge.
func (mr *MockMatcherServiceIMockRecorder) AcceptChallenge(challengedKey, challengerKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptChallenge", reflect.TypeOf((*MockMatcherServiceI)(nil).AcceptChallenge), challengedKey, challengerKey)
}

// AddDependency mocks base method.
func (m *MockMatcherServiceI) AddDependency(service service.ServiceI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDependency", service)
}

// AddDependency indicates an expected call of AddDependency.
func (mr *MockMatcherServiceIMockRecorder) AddDependency(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDependency", reflect.TypeOf((*MockMatcherServiceI)(nil).AddDependency), service)
}

// AddEventListener mocks base method.
func (m *MockMatcherServiceI) AddEventListener(eventVariant service.EventVariant, fn service.EventHandler) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventListener", eventVariant, fn)
	ret0, _ := ret[0].(int)
	return ret0
}

// AddEventListener indicates an expected call of AddEventListener.
func (mr *MockMatcherServiceIMockRecorder) AddEventListener(eventVariant, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventListener", reflect.TypeOf((*MockMatcherServiceI)(nil).AddEventListener), eventVariant, fn)
}

// AddMatch mocks base method.
func (m *MockMatcherServiceI) AddMatch(match *models.Match) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMatch", match)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMatch indicates an expected call of AddMatch.
func (mr *MockMatcherServiceIMockRecorder) AddMatch(match any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMatch", reflect.TypeOf((*MockMatcherServiceI)(nil).AddMatch), match)
}

// Build mocks base method.
func (m *MockMatcherServiceI) Build() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Build")
}

// Build indicates an expected call of Build.
func (mr *MockMatcherServiceIMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockMatcherServiceI)(nil).Build))
}

// Config mocks base method.
func (m *MockMatcherServiceI) Config() service.ConfigI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(service.ConfigI)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockMatcherServiceIMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockMatcherServiceI)(nil).Config))
}

// DeclineChallenge mocks base method.
func (m *MockMatcherServiceI) DeclineChallenge(challengerKey, challengedKey models.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeclineChallenge", challengerKey, challengedKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeclineChallenge indicates an expected call of DeclineChallenge.
func (mr *MockMatcherServiceIMockRecorder) DeclineChallenge(challengerKey, challengedKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeclineChallenge", reflect.TypeOf((*MockMatcherServiceI)(nil).DeclineChallenge), challengerKey, challengedKey)
}

// Dependencies mocks base method.
func (m *MockMatcherServiceI) Dependencies() []service.ServiceI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dependencies")
	ret0, _ := ret[0].([]service.ServiceI)
	return ret0
}

// Dependencies indicates an expected call of Dependencies.
func (mr *MockMatcherServiceIMockRecorder) Dependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dependencies", reflect.TypeOf((*MockMatcherServiceI)(nil).Dependencies))
}

// Dispatch mocks base method.
func (m *MockMatcherServiceI) Dispatch(event service.EventI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Dispatch", event)
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockMatcherServiceIMockRecorder) Dispatch(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockMatcherServiceI)(nil).Dispatch), event)
}

// ExecuteMove mocks base method.
func (m *MockMatcherServiceI) ExecuteMove(matchId string, move *chess.Move) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteMove", matchId, move)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteMove indicates an expected call of ExecuteMove.
func (mr *MockMatcherServiceIMockRecorder) ExecuteMove(matchId, move any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteMove", reflect.TypeOf((*MockMatcherServiceI)(nil).ExecuteMove), matchId, move)
}

// GetChallenge mocks base method.
func (m *MockMatcherServiceI) GetChallenge(challengerKey, receivingClientKey models.Key) (*models.Challenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChallenge", challengerKey, receivingClientKey)
	ret0, _ := ret[0].(*models.Challenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChallenge indicates an expected call of GetChallenge.
func (mr *MockMatcherServiceIMockRecorder) GetChallenge(challengerKey, receivingClientKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChallenge", reflect.TypeOf((*MockMatcherServiceI)(nil).GetChallenge), challengerKey, receivingClientKey)
}

// InboundChallenges mocks base method.
func (m *MockMatcherServiceI) InboundChallenges(challengedKey models.Key) (*set.Set[*models.Challenge], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InboundChallenges", challengedKey)
	ret0, _ := ret[0].(*set.Set[*models.Challenge])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InboundChallenges indicates an expected call of InboundChallenges.
func (mr *MockMatcherServiceIMockRecorder) InboundChallenges(challengedKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InboundChallenges", reflect.TypeOf((*MockMatcherServiceI)(nil).InboundChallenges), challengedKey)
}

// MatchByClientKey mocks base method.
func (m *MockMatcherServiceI) MatchByClientKey(clientKey models.Key) (*models.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchByClientKey", clientKey)
	ret0, _ := ret[0].(*models.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchByClientKey indicates an expected call of MatchByClientKey.
func (mr *MockMatcherServiceIMockRecorder) MatchByClientKey(clientKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchByClientKey", reflect.TypeOf((*MockMatcherServiceI)(nil).MatchByClientKey), clientKey)
}

// MatchById mocks base method.
func (m *MockMatcherServiceI) MatchById(matchId string) (*models.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchById", matchId)
	ret0, _ := ret[0].(*models.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchById indicates an expected call of MatchById.
func (mr *MockMatcherServiceIMockRecorder) MatchById(matchId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchById", reflect.TypeOf((*MockMatcherServiceI)(nil).MatchById), matchId)
}

// OnBuild mocks base method.
func (m *MockMatcherServiceI) OnBuild() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnBuild")
}

// OnBuild indicates an expected call of OnBuild.
func (mr *MockMatcherServiceIMockRecorder) OnBuild() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBuild", reflect.TypeOf((*MockMatcherServiceI)(nil).OnBuild))
}

// OnStart mocks base method.
func (m *MockMatcherServiceI) OnStart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStart")
}

// OnStart indicates an expected call of OnStart.
func (mr *MockMatcherServiceIMockRecorder) OnStart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStart", reflect.TypeOf((*MockMatcherServiceI)(nil).OnStart))
}

// OutboundChallenges mocks base method.
func (m *MockMatcherServiceI) OutboundChallenges(challengerKey models.Key) (*set.Set[*models.Challenge], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboundChallenges", challengerKey)
	ret0, _ := ret[0].(*set.Set[*models.Challenge])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutboundChallenges indicates an expected call of OutboundChallenges.
func (mr *MockMatcherServiceIMockRecorder) OutboundChallenges(challengerKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboundChallenges", reflect.TypeOf((*MockMatcherServiceI)(nil).OutboundChallenges), challengerKey)
}

// RemoveEventListener mocks base method.
func (m *MockMatcherServiceI) RemoveEventListener(eventId int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveEventListener", eventId)
}

// RemoveEventListener indicates an expected call of RemoveEventListener.
func (mr *MockMatcherServiceIMockRecorder) RemoveEventListener(eventId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEventListener", reflect.TypeOf((*MockMatcherServiceI)(nil).RemoveEventListener), eventId)
}

// RequestChallenge mocks base method.
func (m *MockMatcherServiceI) RequestChallenge(challenge *models.Challenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestChallenge", challenge)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestChallenge indicates an expected call of RequestChallenge.
func (mr *MockMatcherServiceIMockRecorder) RequestChallenge(challenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestChallenge", reflect.TypeOf((*MockMatcherServiceI)(nil).RequestChallenge), challenge)
}

// ResignMatch mocks base method.
func (m *MockMatcherServiceI) ResignMatch(matchId string, clientKey models.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResignMatch", matchId, clientKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResignMatch indicates an expected call of ResignMatch.
func (mr *MockMatcherServiceIMockRecorder) ResignMatch(matchId, clientKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResignMatch", reflect.TypeOf((*MockMatcherServiceI)(nil).ResignMatch), matchId, clientKey)
}

// RevokeChallenge mocks base method.
func (m *MockMatcherServiceI) RevokeChallenge(challengerKey, challengedKey models.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeChallenge", challengerKey, challengedKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeChallenge indicates an expected call of RevokeChallenge.
func (mr *MockMatcherServiceIMockRecorder) RevokeChallenge(challengerKey, challengedKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeChallenge", reflect.TypeOf((*MockMatcherServiceI)(nil).RevokeChallenge), challengerKey, challengedKey)
}

// SetParent mocks base method.
func (m *MockMatcherServiceI) SetParent(parent service.ServiceI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetParent", parent)
}

// SetParent indicates an expected call of SetParent.
func (mr *MockMatcherServiceIMockRecorder) SetParent(parent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParent", reflect.TypeOf((*MockMatcherServiceI)(nil).SetParent), parent)
}

// Start mocks base method.
func (m *MockMatcherServiceI) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockMatcherServiceIMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockMatcherServiceI)(nil).Start))
}
