// Code generated by MockGen. DO NOT EDIT.
// Source: ../router_service/router_service.go
//
// Generated by this command:
//
//	mockgen -source=../router_service/router_service.go -destination mocks/router_service_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	service "github.com/CameronHonis/service"
	gomock "go.uber.org/mock/gomock"
)

// MockRouterServiceI is a mock of RouterServiceI interface.
type MockRouterServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockRouterServiceIMockRecorder
}

// MockRouterServiceIMockRecorder is the mock recorder for MockRouterServiceI.
type MockRouterServiceIMockRecorder struct {
	mock *MockRouterServiceI
}

// NewMockRouterServiceI creates a new mock instance.
func NewMockRouterServiceI(ctrl *gomock.Controller) *MockRouterServiceI {
	mock := &MockRouterServiceI{ctrl: ctrl}
	mock.recorder = &MockRouterServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouterServiceI) EXPECT() *MockRouterServiceIMockRecorder {
	return m.recorder
}

// AddDependency mocks base method.
func (m *MockRouterServiceI) AddDependency(service service.ServiceI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDependency", service)
}

// AddDependency indicates an expected call of AddDependency.
func (mr *MockRouterServiceIMockRecorder) AddDependency(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDependency", reflect.TypeOf((*MockRouterServiceI)(nil).AddDependency), service)
}

// AddEventListener mocks base method.
func (m *MockRouterServiceI) AddEventListener(eventVariant service.EventVariant, fn service.EventHandler) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventListener", eventVariant, fn)
	ret0, _ := ret[0].(int)
	return ret0
}

// AddEventListener indicates an expected call of AddEventListener.
func (mr *MockRouterServiceIMockRecorder) AddEventListener(eventVariant, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventListener", reflect.TypeOf((*MockRouterServiceI)(nil).AddEventListener), eventVariant, fn)
}

// Build mocks base method.
func (m *MockRouterServiceI) Build() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Build")
}

// Build indicates an expected call of Build.
func (mr *MockRouterServiceIMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockRouterServiceI)(nil).Build))
}

// Config mocks base method.
func (m *MockRouterServiceI) Config() service.ConfigI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(service.ConfigI)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockRouterServiceIMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockRouterServiceI)(nil).Config))
}

// Dependencies mocks base method.
func (m *MockRouterServiceI) Dependencies() []service.ServiceI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dependencies")
	ret0, _ := ret[0].([]service.ServiceI)
	return ret0
}

// Dependencies indicates an expected call of Dependencies.
func (mr *MockRouterServiceIMockRecorder) Dependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dependencies", reflect.TypeOf((*MockRouterServiceI)(nil).Dependencies))
}

// Dispatch mocks base method.
func (m *MockRouterServiceI) Dispatch(event service.EventI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Dispatch", event)
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockRouterServiceIMockRecorder) Dispatch(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockRouterServiceI)(nil).Dispatch), event)
}

// OnBuild mocks base method.
func (m *MockRouterServiceI) OnBuild() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnBuild")
}

// OnBuild indicates an expected call of OnBuild.
func (mr *MockRouterServiceIMockRecorder) OnBuild() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBuild", reflect.TypeOf((*MockRouterServiceI)(nil).OnBuild))
}

// OnStart mocks base method.
func (m *MockRouterServiceI) OnStart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStart")
}

// OnStart indicates an expected call of OnStart.
func (mr *MockRouterServiceIMockRecorder) OnStart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStart", reflect.TypeOf((*MockRouterServiceI)(nil).OnStart))
}

// RemoveEventListener mocks base method.
func (m *MockRouterServiceI) RemoveEventListener(eventId int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveEventListener", eventId)
}

// RemoveEventListener indicates an expected call of RemoveEventListener.
func (mr *MockRouterServiceIMockRecorder) RemoveEventListener(eventId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEventListener", reflect.TypeOf((*MockRouterServiceI)(nil).RemoveEventListener), eventId)
}

// SetParent mocks base method.
func (m *MockRouterServiceI) SetParent(parent service.ServiceI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetParent", parent)
}

// SetParent indicates an expected call of SetParent.
func (mr *MockRouterServiceIMockRecorder) SetParent(parent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParent", reflect.TypeOf((*MockRouterServiceI)(nil).SetParent), parent)
}

// Start mocks base method.
func (m *MockRouterServiceI) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockRouterServiceIMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRouterServiceI)(nil).Start))
}

// StartWSServer mocks base method.
func (m *MockRouterServiceI) StartWSServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartWSServer")
}

// StartWSServer indicates an expected call of StartWSServer.
func (mr *MockRouterServiceIMockRecorder) StartWSServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWSServer", reflect.TypeOf((*MockRouterServiceI)(nil).StartWSServer))
}
