// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CameronHonis/chess-arbitrator/sub_service (interfaces: SubscriptionServiceI)
//
// Generated by this command:
//
//	mockgen -destination mocks/sub_service_mock.go -package mocks github.com/CameronHonis/chess-arbitrator/sub_service SubscriptionServiceI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "github.com/CameronHonis/chess-arbitrator/models"
	service "github.com/CameronHonis/service"
	set "github.com/CameronHonis/set"
	gomock "go.uber.org/mock/gomock"
	reflect "reflect"
)

// MockSubscriptionServiceI is a mock of SubscriptionServiceI interface.
type MockSubscriptionServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionServiceIMockRecorder
}

// MockSubscriptionServiceIMockRecorder is the mock recorder for MockSubscriptionServiceI.
type MockSubscriptionServiceIMockRecorder struct {
	mock *MockSubscriptionServiceI
}

// NewMockSubscriptionServiceI creates a new mock instance.
func NewMockSubscriptionServiceI(ctrl *gomock.Controller) *MockSubscriptionServiceI {
	mock := &MockSubscriptionServiceI{ctrl: ctrl}
	mock.recorder = &MockSubscriptionServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionServiceI) EXPECT() *MockSubscriptionServiceIMockRecorder {
	return m.recorder
}

// AddDependency mocks base method.
func (m *MockSubscriptionServiceI) AddDependency(arg0 service.ServiceI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDependency", arg0)
}

// AddDependency indicates an expected call of AddDependency.
func (mr *MockSubscriptionServiceIMockRecorder) AddDependency(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDependency", reflect.TypeOf((*MockSubscriptionServiceI)(nil).AddDependency), arg0)
}

// AddEventListener mocks base method.
func (m *MockSubscriptionServiceI) AddEventListener(arg0 service.EventVariant, arg1 service.EventHandler) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventListener", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// AddEventListener indicates an expected call of AddEventListener.
func (mr *MockSubscriptionServiceIMockRecorder) AddEventListener(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventListener", reflect.TypeOf((*MockSubscriptionServiceI)(nil).AddEventListener), arg0, arg1)
}

// Build mocks base method.
func (m *MockSubscriptionServiceI) Build() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Build")
}

// Build indicates an expected call of Build.
func (mr *MockSubscriptionServiceIMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockSubscriptionServiceI)(nil).Build))
}

// ClientKeysSubbedToTopic mocks base method.
func (m *MockSubscriptionServiceI) ClientKeysSubbedToTopic(arg0 models.MessageTopic) *set.Set[models.Key] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientKeysSubbedToTopic", arg0)
	ret0, _ := ret[0].(*set.Set[models.Key])
	return ret0
}

// ClientKeysSubbedToTopic indicates an expected call of ClientKeysSubbedToTopic.
func (mr *MockSubscriptionServiceIMockRecorder) ClientKeysSubbedToTopic(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientKeysSubbedToTopic", reflect.TypeOf((*MockSubscriptionServiceI)(nil).ClientKeysSubbedToTopic), arg0)
}

// Config mocks base method.
func (m *MockSubscriptionServiceI) Config() service.ConfigI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(service.ConfigI)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockSubscriptionServiceIMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockSubscriptionServiceI)(nil).Config))
}

// Dependencies mocks base method.
func (m *MockSubscriptionServiceI) Dependencies() []service.ServiceI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dependencies")
	ret0, _ := ret[0].([]service.ServiceI)
	return ret0
}

// Dependencies indicates an expected call of Dependencies.
func (mr *MockSubscriptionServiceIMockRecorder) Dependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dependencies", reflect.TypeOf((*MockSubscriptionServiceI)(nil).Dependencies))
}

// Dispatch mocks base method.
func (m *MockSubscriptionServiceI) Dispatch(arg0 service.EventI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Dispatch", arg0)
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockSubscriptionServiceIMockRecorder) Dispatch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockSubscriptionServiceI)(nil).Dispatch), arg0)
}

// OnBuild mocks base method.
func (m *MockSubscriptionServiceI) OnBuild() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnBuild")
}

// OnBuild indicates an expected call of OnBuild.
func (mr *MockSubscriptionServiceIMockRecorder) OnBuild() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBuild", reflect.TypeOf((*MockSubscriptionServiceI)(nil).OnBuild))
}

// OnStart mocks base method.
func (m *MockSubscriptionServiceI) OnStart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStart")
}

// OnStart indicates an expected call of OnStart.
func (mr *MockSubscriptionServiceIMockRecorder) OnStart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStart", reflect.TypeOf((*MockSubscriptionServiceI)(nil).OnStart))
}

// RemoveEventListener mocks base method.
func (m *MockSubscriptionServiceI) RemoveEventListener(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveEventListener", arg0)
}

// RemoveEventListener indicates an expected call of RemoveEventListener.
func (mr *MockSubscriptionServiceIMockRecorder) RemoveEventListener(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEventListener", reflect.TypeOf((*MockSubscriptionServiceI)(nil).RemoveEventListener), arg0)
}

// SetParent mocks base method.
func (m *MockSubscriptionServiceI) SetParent(arg0 service.ServiceI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetParent", arg0)
}

// SetParent indicates an expected call of SetParent.
func (mr *MockSubscriptionServiceIMockRecorder) SetParent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParent", reflect.TypeOf((*MockSubscriptionServiceI)(nil).SetParent), arg0)
}

// Start mocks base method.
func (m *MockSubscriptionServiceI) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockSubscriptionServiceIMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSubscriptionServiceI)(nil).Start))
}

// SubClient mocks base method.
func (m *MockSubscriptionServiceI) SubClient(arg0 models.Key, arg1 models.MessageTopic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubClient", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubClient indicates an expected call of SubClient.
func (mr *MockSubscriptionServiceIMockRecorder) SubClient(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubClient", reflect.TypeOf((*MockSubscriptionServiceI)(nil).SubClient), arg0, arg1)
}

// SubbedTopics mocks base method.
func (m *MockSubscriptionServiceI) SubbedTopics(arg0 models.Key) *set.Set[models.MessageTopic] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubbedTopics", arg0)
	ret0, _ := ret[0].(*set.Set[models.MessageTopic])
	return ret0
}

// SubbedTopics indicates an expected call of SubbedTopics.
func (mr *MockSubscriptionServiceIMockRecorder) SubbedTopics(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubbedTopics", reflect.TypeOf((*MockSubscriptionServiceI)(nil).SubbedTopics), arg0)
}

// UnsubClient mocks base method.
func (m *MockSubscriptionServiceI) UnsubClient(arg0 models.Key, arg1 models.MessageTopic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubClient", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubClient indicates an expected call of UnsubClient.
func (mr *MockSubscriptionServiceIMockRecorder) UnsubClient(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubClient", reflect.TypeOf((*MockSubscriptionServiceI)(nil).UnsubClient), arg0, arg1)
}

// UnsubClientFromAll mocks base method.
func (m *MockSubscriptionServiceI) UnsubClientFromAll(arg0 models.Key) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnsubClientFromAll", arg0)
}

// UnsubClientFromAll indicates an expected call of UnsubClientFromAll.
func (mr *MockSubscriptionServiceIMockRecorder) UnsubClientFromAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubClientFromAll", reflect.TypeOf((*MockSubscriptionServiceI)(nil).UnsubClientFromAll), arg0)
}
