package server

const LOG_PROMPTS = true
const LOG_MESSAGES = true

type MessageTopic uint8

const (
	MESSAGE_TOPIC_NONE MessageTopic = iota
	MESSAGE_TOPIC_AUTH
	MESSAGE_TOPIC_MATCHMAKING
)

type PromptType uint8

const (
	PROMPT_TYPE_NONE PromptType = iota
	PROMPT_TYPE_INIT_CLIENT
	PROMPT_TYPE_SUBSCRIBE_TO_TOPIC
	PROMPT_TYPE_UNSUBSCRIBE_TO_TOPIC
	PROMPT_TYPE_TRANSFER_MESSAGE
)
