// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CameronHonis/chess-arbitrator/router_service (interfaces: RouterServiceI)
//
// Generated by this command:
//
//	mockgen -destination mock/router_service_mock.go . RouterServiceI
//

// Package mock_router_service is a generated GoMock package.
package mock_router_service

import (
	reflect "reflect"

	service "github.com/CameronHonis/service"
	gomock "go.uber.org/mock/gomock"
)

// MockRouterServiceI is a mock of RouterServiceI interface.
type MockRouterServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockRouterServiceIMockRecorder
}

// MockRouterServiceIMockRecorder is the mock recorder for MockRouterServiceI.
type MockRouterServiceIMockRecorder struct {
	mock *MockRouterServiceI
}

// NewMockRouterServiceI creates a new mock instance.
func NewMockRouterServiceI(ctrl *gomock.Controller) *MockRouterServiceI {
	mock := &MockRouterServiceI{ctrl: ctrl}
	mock.recorder = &MockRouterServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouterServiceI) EXPECT() *MockRouterServiceIMockRecorder {
	return m.recorder
}

// AddDependency mocks base method.
func (m *MockRouterServiceI) AddDependency(arg0 service.ServiceI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDependency", arg0)
}

// AddDependency indicates an expected call of AddDependency.
func (mr *MockRouterServiceIMockRecorder) AddDependency(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDependency", reflect.TypeOf((*MockRouterServiceI)(nil).AddDependency), arg0)
}

// AddEventListener mocks base method.
func (m *MockRouterServiceI) AddEventListener(arg0 service.EventVariant, arg1 service.EventHandler) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventListener", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// AddEventListener indicates an expected call of AddEventListener.
func (mr *MockRouterServiceIMockRecorder) AddEventListener(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventListener", reflect.TypeOf((*MockRouterServiceI)(nil).AddEventListener), arg0, arg1)
}

// Config mocks base method.
func (m *MockRouterServiceI) Config() service.ConfigI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(service.ConfigI)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockRouterServiceIMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockRouterServiceI)(nil).Config))
}

// Dependencies mocks base method.
func (m *MockRouterServiceI) Dependencies() []service.ServiceI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dependencies")
	ret0, _ := ret[0].([]service.ServiceI)
	return ret0
}

// Dependencies indicates an expected call of Dependencies.
func (mr *MockRouterServiceIMockRecorder) Dependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dependencies", reflect.TypeOf((*MockRouterServiceI)(nil).Dependencies))
}

// Dispatch mocks base method.
func (m *MockRouterServiceI) Dispatch(arg0 service.EventI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Dispatch", arg0)
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockRouterServiceIMockRecorder) Dispatch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockRouterServiceI)(nil).Dispatch), arg0)
}

// OnStart mocks base method.
func (m *MockRouterServiceI) OnStart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStart")
}

// OnStart indicates an expected call of OnStart.
func (mr *MockRouterServiceIMockRecorder) OnStart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStart", reflect.TypeOf((*MockRouterServiceI)(nil).OnStart))
}

// RemoveEventListener mocks base method.
func (m *MockRouterServiceI) RemoveEventListener(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveEventListener", arg0)
}

// RemoveEventListener indicates an expected call of RemoveEventListener.
func (mr *MockRouterServiceIMockRecorder) RemoveEventListener(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEventListener", reflect.TypeOf((*MockRouterServiceI)(nil).RemoveEventListener), arg0)
}

// SetParent mocks base method.
func (m *MockRouterServiceI) SetParent(arg0 service.ServiceI) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetParent", arg0)
}

// SetParent indicates an expected call of SetParent.
func (mr *MockRouterServiceIMockRecorder) SetParent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParent", reflect.TypeOf((*MockRouterServiceI)(nil).SetParent), arg0)
}

// Start mocks base method.
func (m *MockRouterServiceI) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockRouterServiceIMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRouterServiceI)(nil).Start))
}

// StartWSServer mocks base method.
func (m *MockRouterServiceI) StartWSServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartWSServer")
}

// StartWSServer indicates an expected call of StartWSServer.
func (mr *MockRouterServiceIMockRecorder) StartWSServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWSServer", reflect.TypeOf((*MockRouterServiceI)(nil).StartWSServer))
}
